### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Captianbeau** [Captianbeau/WeatherApp#3]
# CSS
## User Story
AS A Developer 
I WANT a CSS 
SO THAT the webpage looks pleasing to view
## Acceptance Criteria
   GIVEN a CSS
WHEN I view the web-page 
THEN it looks appealing
THEN it is easy to read and follow
THEN it is reactive

**Comment by Dhairya1Gupta** [comment]
I would like to contribute in this project.
I have done similar task in my project.
Please assign me this issue.

**Comment by Captianbeau** [comment]
@Dhairya1Gupta \
Thank you for the offer however, this is a homework assignment and I am meant to do it by myself.
